---
title: "paper"
author: 
  - Pascal Lee Slew
  - Yunkyung Park
thanks: "Code and data are available at: https://github.com/Pascal-304/dhs_analysis."
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "Four sentences"
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, echo=FALSE, message=FALSE}
# install.packages('bookdown')
# install.packages("stringr")
library(stringr) 
library(dplyr)
library(tidyverse) 
library(janitor)
library(ggplot2)
library(knitr)
library(kableExtra)
library(bookdown)
```

```{r readdata, echo=FALSE}
ghana <- read_csv('data/cleaned_data.csv', show_col_types = FALSE)
```

# Introduction

# Data

```{r total, echo=FALSE, fig.cap="Data"}
ghana %>%
  mutate(
    character = factor(character,
                       levels = c("Residence",
                                "Region",
                                "Mother\'s_education",
                                "Work_status",
                                "Occupation",
                                "Employment_status",
                                "Total"
                                )
                       )
           ) %>%
  group_by(character) %>%
  summarise(sum = sum(number_of_employed_women))
```

Table \@ref(tab:total) shows that 3,566 participated the survey, but there are 3 whom did not answer their employment status, etc. 

```{r data, echo=FALSE}
ghana %>%
  select(background, no_child_under_six, one_more_child_under_six, caretaker_respondent, character) %>%
  slice(1:10) %>%
  kable(caption='A subset of key features',
        col.names = c('Background', 'No child under six', '1+ child under six', 
                      'Child\'s caretaker - respondent', 'Character'),
        digits = 1,
        booktabs = FALSE,
        linesep = "")
```

# Results

```{r, echo=FALSE}
# Urban vs Rural

# Obtain subset of dataset for residence area
residence <- ghana %>% 
  filter(character == 'Residence')

# look at survey respondents distribution in urban and rural areas
residence %>% 
  ggplot(aes(x = background, y = number_of_employed_women)) +
  geom_bar(stat = 'identity', fill = "burlywood") +
  labs(x = "Area",
       y = "Number of employed women") +
  theme_minimal()
```


```{r, echo=FALSE}
# region subdataset
region <- ghana %>% 
  filter(character == "Region") %>% 
  mutate(background = recode(background,
                             'Western' = 'Western',
                             'Central' = 'Central',
                             'Greater_Accra' = 'Greater Accra',
                             'Volta' = 'Volta',
                             'Eastern' = 'Eastern',
                             'Ashanti' = 'Ashanti',
                             'Brong_Ahafo' = 'Brong Ahafo',
                             'Northen' = 'Northern',
                             'Upper_West' = 'Upper West',
                             'Upper_East' = 'Upper East'))

# number of survey respondents in the different administrative regions
region %>% 
  ggplot(aes(x = background,
             y = number_of_employed_women)) +
  geom_bar(stat = 'identity',
           fill = 'burlywood') +
  labs(x = "Administrative regions",
       y = "Number of employed women") +
  theme_minimal()
```



```{r, echo = FALSE}
# make dataset in long format
resid_long <- residence %>% 
  select(-c(character)) %>% 
  pivot_longer(!background, names_to = "variables", values_to = "percentage")

# create label names list
label_list <- list('no_child_under_six' = "No child under six", 
                   'one_more_child_under_six' = "One or more child under six")

labellers <- function(variable, value) {
  return(label_list[value])
}

# plot bar graph
resid_long %>% 
  filter(variables == 'no_child_under_six' | variables == 'one_more_child_under_six') %>% 
  ggplot(aes(x = background, 
             y = percentage,
             fill = variables)) +
  geom_bar(stat = 'identity',
           position = 'dodge') +
  labs(x = "Area",
       y = "Percentage of women",
       fill = "Children under six") +
  theme_minimal() +
  scale_fill_brewer() +
  theme(legend.position = "bottom")

# need to recode names
# change legends name
```


```{r}
# caretaker aspect

# make dataset into long format
# rename 
caretaker <- residence %>% 
  select(-c(character, no_child_under_six, one_more_child_under_six, total, number_of_employed_women)) %>% 
  pivot_longer(!background, names_to = "caretakers", values_to = "percentage") %>% 
  mutate(caretakers = recode(caretakers,
                             'caretaker_respondent' = 'respondent',
                             'caretaker_partner' = 'partner',
                             'caretaker_other_relative' = 'other relative',
                             'caretaker_other_male_child' = 'other male child',
                             'caretaker_other_female_child' = 'other female child',
                             'caretaker_other' = 'other',
                             'caretaker_not_worked_since_birth' = 'not worked since birth',
                             'caretaker_neighbor' = 'neighbour',
                             'caretaker_missing' = 'missing',
                             'caretaker_hired' = 'hired',
                             'caretaker_child_in_school' = 'child in school'))

# plot bar graph
caretaker %>% 
  ggplot(aes(x = caretakers, 
             y = percentage,
             fill = background)) +
  geom_bar(stat = 'identity',
           position = "dodge") +
  labs(x = "Caretaker",
       y = "Percentage of women",
       fill = "Area") +
  theme_minimal() +
  coord_flip() +
  scale_fill_brewer(palette = "Set1") +
  theme(legend.position = "bottom")

```

## Also comparison among the different administrative regions

```{r, echo = FALSE}
# make dataset into long format
# recode names
child <- region %>% 
  select(-c(character, total)) %>% 
  pivot_longer(!background, names_to = "x", values_to = "percentage") %>% 
  mutate(x = recode(x,
                    'caretaker_respondent' = 'respondent',
                    'caretaker_partner' = 'partner',
                    'caretaker_other_relative' = 'other relative',
                    'caretaker_other_male_child' = 'other male child',
                    'caretaker_other_female_child' = 'other female child',
                    'caretaker_other' = 'other',
                    'caretaker_not_worked_since_birth' = 'not worked since birth',
                    'caretaker_neighbor' = 'neighbour',
                    'caretaker_missing' = 'missing',
                    'caretaker_hired' = 'hired',
                    'caretaker_child_in_school' = 'child in school',
                    'no_child_under_six' = 'no child under six',
                    'one_more_child_under_six' = 'one or more child under six',
                    'number_of_employed_women' = 'number of employed women'))

# plot bar graph for caretaker comparisons and administrative regions
child %>% 
  filter(x != 'number of employed women', x != 'no child under six', x!= 'one or more child under six') %>% 
  ggplot(aes(x = x,
             y = percentage,
             fill = background)) +
  geom_bar(stat = 'identity') + 
  labs(x = "caretaker",
       y = "percentage of XXX",
       fill = "Administrative regions") +
  theme_minimal() +
  coord_flip() +
  facet_wrap(~background) +
  theme(legend.position = "bottom")

```



```{r, echo = FALSE}
# number of employed women selected in the admiistrative regions
child %>% 
  filter(x == "number of employed women") %>% 
  ggplot(aes(x = x,
             y = percentage,
             fill = background)) +
  geom_bar(stat = 'identity',
           position = 'dodge') +
  labs(x = 'Administrative regions',
       y = 'Number of employed women') +
  theme_minimal() +
  scale_fill_brewer(palette = 'Set3') +
  theme(legend.position = "bottom")
```





```{r, echo = FALSE}
# looking at the number of employed women selected in the different administrative regions
# with the child under six
child %>% 
  filter(x == "no child under six" | x == "one or more child under six") %>% 
  ggplot(aes(x = x,
             y = percentage,
             fill = background)) +
  geom_bar(stat = 'identity') +
  labs(x = "child",
       y = "percentage of XXX",
       fill = "Administrative regions") +
  theme_minimal() +
  coord_flip() +
  facet_wrap(~background)

```





# Discussions

## Limitation and weaknesses

The number does not add up to 100. (truncation error)

\newpage

# References